<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <Deterministic>false</Deterministic>
    <AssemblyVersion>1.0.*</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Configurations>Debug;Release;EasyTest</Configurations>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>02a25be3-31d3-421f-80a4-b0b8bd59371d</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Model.xafml" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Model.xafml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Drawing.Skia" Version="25.2.*" />
    <PackageReference Include="DevExpress.ExpressApp.Api.EFCore.All" Version="25.2.*" />
    <PackageReference Include="DevExpress.ExpressApp.Blazor" Version="25.2.*" />
    <PackageReference Include="DevExpress.ExpressApp.CodeAnalysis" Version="25.2.*" />
    <PackageReference Include="DevExpress.ExpressApp.Dashboards.Blazor" Version="25.2.*" />
    <PackageReference Include="DevExpress.ExpressApp.Validation" Version="25.2.*" />
    <PackageReference Include="DevExpress.ExpressApp.Validation.Blazor" Version="25.2.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.9.0" />
    
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\QuickHaul.Module\QuickHaul.Module.csproj" />
  </ItemGroup>
</Project>
